apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: admission-webhooks
  name: admission-webhooks
  namespace: admission-webhooks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-webhooks
  template:
    metadata:
      labels:
        app: admission-webhooks
    spec:
      containers:
      - image: registry.harrisonkiang.com/container-registry/admission-webhooks:d3554363a967db4be8f0a3615445b9a4a666c630
        name: admission-webhooks
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        env:
        - name: SSL_KEYFILE
          value: /home/ssl/tls.key
        - name: SSL_CERTFILE
          value: /home/ssl/tls.crt
        volumeMounts:
          - name: ssl
            mountPath: "/home/ssl"
            readOnly: true
      volumes:
        - name: ssl
          secret:
            secretName: harrisonkiang-dot-com-wildcard-tls
