apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: admission-webhooks
  namespace: admission-webhooks
spec:
  rules:
  - host: admission-webhooks.harrisonkiang.com
    http:
      paths:
      - backend:
          serviceName: admission-webhooks
          servicePort: 80
        path: /
  tls:
  - hosts:
    - admission-webhooks.harrisonkiang.com
    secretName: harrisonkiang-dot-com-wildcard-tls