apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: admission-webhooks.harrisonkiang.com
  namespace: admission-webhooks
webhooks:
  - name: admission-webhooks.harrisonkiang.com
    failurePolicy: Fail
    clientConfig:
        url: https://admission-webhooks.harrisonkiang.com/validate/deployments
    rules:
      - apiGroups: ["apps"]
        resources:
          - "deployments"
        apiVersions:
          - "*"
        operations:
          - CREATE
