apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhooks
  namespace: admission-webhooks
webhooks:
  - name: admission-webhooks
    failurePolicy: Fail
    clientConfig:
      service:
        name: admission-webhooks
        namespace: admission-webhooks
        path: /validate/deployments
    rules:
      - apiGroups: ["apps"]
        resources:
          - "deployments"
        apiVersions:
          - "*"
        operations:
          - CREATE